# Generated by Django 4.2.20 on 2025-03-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoring",
            name="patient",
        ),
        migrations.DeleteModel(
            name="Diagnostic",
        ),
        migrations.DeleteModel(
            name="Monitoring",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
