# Generated by Django 4.2.20 on 2025-03-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='absolute_neutrophile_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='absolute_neutrophile_count_units',
            field=models.CharField(blank=True, choices=[('CELLS/UL', 'cells/microliter'), ('CELLS/L', 'cells/Liter')], default='CELLS/UL', help_text="Units for the patient's absolute neutrophile count", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(blank=True, editable=False, help_text="Patient's BMI (computed)", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='bone_imaging_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='bone_lesions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='caregiver_availability_status',
            field=models.BooleanField(default=False, help_text='Is there an available caregiver for the patient?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='clonal_bone_marrow_plasma_cells_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='clonal_plasma_cells',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='consent_capability',
            field=models.BooleanField(default=True, help_text='Does the patient have cognitive ability to consent?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='contraceptive_use',
            field=models.BooleanField(default=False, help_text='Does the patient use contraceptives?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='creatinine_clearance_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cytogenic_markers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diastolic_blood_pressure',
            field=models.IntegerField(blank=True, help_text="Patient's diastolic blood pressure", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.TextField(blank=True, default='multiple myeloma', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ecog_performance_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ejection_fraction',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='estimated_glomerular_filtration_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_line_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_line_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_line_therapy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='flipi_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='flipi_score_options',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gelf_criteria_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('UN', 'Unknown'), ('', 'Empty')], help_text="What is the patient's gender (leave empty if there is no requirement)?", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heartrate',
            field=models.IntegerField(blank=True, help_text="Patient's heart rate", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='heartrate_variability',
            field=models.IntegerField(blank=True, help_text="Patient's heart rate variability", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.FloatField(blank=True, help_text="Patient's height", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='height_units',
            field=models.CharField(blank=True, choices=[('cm', 'Centimeters'), ('m', 'Meters'), ('ft', 'Feet'), ('in', 'Inches')], default='cm', help_text="Units for the patient's height", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hemoglobin_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hemoglobin_level_units',
            field=models.CharField(blank=True, choices=[('G/DL', 'g/deciliter'), ('G/L', 'g/Liter')], default='G/DL', help_text="Units for the patient's hemoglobin level", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='kappa_flc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='karnofsky_performance_score',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lactate_dehydrogenase_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='lambda_flc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='later_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='later_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='later_therapy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='line_of_therapy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='liver_enzyme_levels_alt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='liver_enzyme_levels_ast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='meets_crab',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='meets_slim',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='molecular_markers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='monoclonal_protein_serum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='monoclonal_protein_urine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_concomitant_medication_status',
            field=models.BooleanField(default=True, help_text='Does the patient have concomitant medication?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_geographic_exposure_risk',
            field=models.BooleanField(default=True, help_text='Has the patient had geographic exposure to risk?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_hepatitis_b_status',
            field=models.BooleanField(default=True, help_text='Does the patient has had Hepatitis B (HBV)?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_hepatitis_c_status',
            field=models.BooleanField(default=True, help_text='Does the patient has had Hepatitis C (HCV)?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_hiv_status',
            field=models.BooleanField(default=True, help_text='Does the patient has had HIV?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_mental_health_disorder_status',
            field=models.BooleanField(default=True, help_text='Does the patient have a mental health disorder?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_other_active_malignancies',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_pregnancy_or_lactation_status',
            field=models.BooleanField(default=True, help_text='Does the patient self assess as not pregnant or lactating?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_substance_use_status',
            field=models.BooleanField(default=True, help_text='Does the patient use substances?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='no_tobacco_use_status',
            field=models.BooleanField(default=True, help_text='Does the patient use tobacco?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='peripheral_neuropathy_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='plasma_cell_leukemia',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='platelet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='platelet_count_units',
            field=models.CharField(blank=True, choices=[('CELLS/UL', 'cells/microliter'), ('CELLS/L', 'cells/Liter')], default='CELLS/UL', help_text="Units for the patient's platelet count", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pregnancy_test_result',
            field=models.BooleanField(default=False, help_text='Does the female patient of childbearing age have a negative test result for pregnancy?'),
        ),
        migrations.AddField(
            model_name='patient',
            name='prior_therapy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='progression',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pulmonary_function_test_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='red_blood_cell_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='red_blood_cell_count_units',
            field=models.CharField(blank=True, choices=[('CELLS/UL', 'cells/microliter'), ('CELLS/L', 'cells/Liter')], default='CELLS/L', help_text="Units for the patient's red blood cell count", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='relapse_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='remission_duration_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_line_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_line_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='second_line_therapy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_bilirubin_level_direct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_bilirubin_level_direct_units',
            field=models.CharField(blank=True, choices=[('MG/DL', 'mg/dL'), ('MICROMOLES/L', 'micromoles/L')], default='MG/DL', help_text="Units for the patient's direct serum bilirubin level", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_bilirubin_level_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_bilirubin_level_total_units',
            field=models.CharField(blank=True, choices=[('MG/DL', 'mg/dL'), ('MICROMOLES/L', 'micromoles/L')], default='MG/DL', help_text="Units for the patient's total serum bilirubin level", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_calcium_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_calcium_level_units',
            field=models.CharField(blank=True, choices=[('MG/DL', 'mg/dL'), ('MICROMOLES/L', 'micromoles/L')], default='MG/DL', help_text="Units for the patient's serum calcium level", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_creatinine_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='serum_creatinine_level_units',
            field=models.CharField(blank=True, choices=[('MG/DL', 'mg/dL'), ('MICROMOLES/L', 'micromoles/L')], default='MG/DL', help_text="Units for the patient's serum creatinine level", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='stem_cell_transplant_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='systolic_blood_pressure',
            field=models.IntegerField(blank=True, help_text="Patient's systolic blood pressure", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='therapy_lines_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='treatment_refractory_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tumor_grade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='washout_period_duration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.FloatField(blank=True, help_text="Patient's weight", null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_units',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', help_text="Units for the patient's weight", max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='white_blood_cell_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='white_blood_cell_count_units',
            field=models.CharField(blank=True, choices=[('CELLS/UL', 'cells/microliter'), ('CELLS/L', 'cells/Liter')], default='CELLS/L', help_text="Units for the patient's white blood cell count", max_length=10, null=True),
        ),
    ]
